### ISSUE TITLE
Avoid memory allocation in backtrace printing

### ISSUE THREAD

**Issue by PhilMiller** [AMReX-Codes/amrex#3038]
When a backtrace is generated in the signal handler code, it calls through `malloc` to buffer the tracing records and the text to be printed. I encountered a case where a signal was raise inside `malloc` itself, due to an earlier heap corruption:

```
(gdb) bt
#0  __lll_lock_wait_private (futex=0x7f903e20fb80 <main_arena>) at ./lowlevellock.c:35
#1  0x00007f903e0bd32b in __GI___libc_malloc (bytes=bytes@entry=472) at malloc.c:3064
#2  0x00007f903e0a592e in __fopen_internal (is32=1, mode=0x7f8fc58894a5 "w", filename=0x7ffd17c6e720 "Backtrace.0") at iofopen.c:58
#3  _IO_new_fopen (filename=0x7ffd17c6e720 "Backtrace.0", mode=0x7f8fc58894a5 "w") at iofopen.c:86
#4  0x00007f8fc52c3e79 in amrex::BLBackTrace::handler (s=6) at /home/ubuntu/repos/amrex/Src/Base/AMReX_BLBackTrace.cpp:92
#5  <signal handler called>
#6  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#7  0x00007f903e045859 in __GI_abort () at abort.c:79
#8  0x00007f903e0b026e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f903e1da298 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#9  0x00007f903e0b82fc in malloc_printerr (str=str@entry=0x7f903e1dca50 "malloc(): invalid size (unsorted)") at malloc.c:5347
#10 0x00007f903e0bb0b4 in _int_malloc (av=av@entry=0x7f903e20fb80 <main_arena>, bytes=bytes@entry=344) at malloc.c:3736
#11 0x00007f903e0bd299 in __GI___libc_malloc (bytes=344) at malloc.c:3066
#12 0x00007f9029179b39 in operator new(unsigned long) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007f8fc4d10113 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::pair<int, int> const, amrex::ParticleTile<0, 0, 4, 0, std::allocator> > > >::allocate (this=0xb5c3d40, __n=1)
    at /usr/include/c++/9/ext/new_allocator.h:114
#14 0x00007f8fc4d0d78e in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<std::pair<int, int> const, amrex::ParticleTile<0, 0, 4, 0, std::allocator> > > > >::allocate (__a=..., __n=1)
    at /usr/include/c++/9/bits/alloc_traits.h:443
```

What's going on here is that the re-entrant `malloc` call will spin forever trying to take a lock that the outer call already holds. Thus, attempts at generating a crash report turn into a hang.

In development settings, this is mildly inconvenient. If a similar event were to occur on a production system at scale, it could potentially consume many node hours from a scarce budget before the job reaches its time limit.

My suggested solution is to pre-allocate a buffer for these purposes in each process at startup, and use that instead of attempting dynamic allocation within a signal handler. I recognize that the commonly-used handler code makes other calls that may not be async-signal-safe, but this is one that actually, observably bites us.

**Comment by asalmgren** [comment]
Closing this issue due to lack of activity.  Please re-open it if you feel there is is still an issue!

**Comment by PhilMiller** [comment]
This one should probably stay open and get addressed, due to the mentioned risk of hanging a large job.
