### ISSUE TITLE
GNUmake broken

### ISSUE THREAD

**Issue by zingale** [AMReX-Codes/amrex#3178]
PR #3177 seems to have broken compilation in Castro.  I now get:

```
Traceback (most recent call last):
  File "/home/zingale/development/Microphysics/networks/update_headers.py", line 48, in <module>
    main()
  File "/home/zingale/development/Microphysics/networks/update_headers.py", line 38, in main
    os.makedirs(args.odir)
  File "/usr/lib64/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib64/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/castro_sources'
```

**Comment by zingale** [comment]
I suspect that this is because the variable TmpBuildDir was renamed for some reason.  Can we revert it? or add an alias so all of the application codes don't need to be changed?

**Comment by mirenradia** [comment]
Sorry about making this breaking change. The reason I changed the name was for consistency with other user-specifiable makefile variable names.
